-- 코드를 입력하세요
SELECT DISTINCT C.CAR_ID, C.CAR_TYPE, FLOOR(30*DAILY_FEE*(1 - DISCOUNT_RATE/100)) AS FEE
    FROM CAR_RENTAL_COMPANY_CAR AS C
    JOIN CAR_RENTAL_COMPANY_RENTAL_HISTORY AS H
      ON C.CAR_ID = H.CAR_ID 
    JOIN CAR_RENTAL_COMPANY_DISCOUNT_PLAN AS D
      ON C.CAR_TYPE = D.CAR_TYPE AND
         D.DURATION_TYPE = '30일 이상'
    WHERE C.CAR_TYPE IN ('세단', 'SUV') 
          AND C.CAR_ID NOT IN (SELECT CAR_ID 
                                 FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
                                WHERE NOT (END_DATE < '2022-11-01' OR 
                                           '2022-11-30' < START_DATE))
    HAVING FEE BETWEEN 500000 AND 2000000-1
    ORDER BY 3 DESC, 2, 1 DESC;